# Generated by Django 5.0.6 on 2024-07-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('all_description', models.TextField(blank=True, null=True, verbose_name='Полное описание')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Продолжительность')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Изображение')),
                ('old_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Cтарая цена')),
                ('new_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Новая цена')),
                ('link', models.TextField(blank=True, null=True, verbose_name='Ссылка на сайт')),
            ],
            options={
                'verbose_name': 'Медитация',
                'verbose_name_plural': 'Медитации',
                'db_table': 'meditations',
            },
        ),
    ]
