# Generated by Django 5.0.6 on 2024-07-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meditation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meditations_images', verbose_name='Изображение'),
        ),
    ]
