# Generated by Django 5.0.6 on 2024-08-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditations', '0002_alter_meditation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditation',
            name='id_modal',
            field=models.TextField(blank=True, null=True, verbose_name='id для модального окна (без #)'),
        ),
        migrations.AddField(
            model_name='meditation',
            name='link_web',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на сайт'),
        ),
        migrations.AlterField(
            model_name='meditation',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='id для модального окна (с #)'),
        ),
    ]
