# Generated by Django 5.0.6 on 2024-07-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/goods_images', verbose_name='Изображение'),
        ),
    ]
