# Generated by Django 5.0.6 on 2024-07-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicums', '0004_remove_products_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Практикум', 'verbose_name_plural': 'Практикумы'},
        ),
        migrations.AddField(
            model_name='products',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Продолжительность'),
        ),
        migrations.AlterModelTable(
            name='products',
            table='practicums',
        ),
    ]
