# Generated by Django 5.0.6 on 2024-07-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicums', '0006_alter_products_new_price_alter_products_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='all_description',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
    ]
