# Generated by Django 5.0.6 on 2024-07-24 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practicums', '0007_alter_products_all_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Practicums',
        ),
    ]
