# Generated by Django 5.0.6 on 2024-07-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicums', '0008_rename_products_practicums'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicums',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
    ]
