# Generated by Django 5.0.6 on 2024-07-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicums', '0009_practicums_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicums',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на сайт'),
        ),
    ]
