# Generated by Django 5.0.6 on 2024-08-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicums', '0011_practicums_id_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicums',
            name='link_web',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на сайт'),
        ),
        migrations.AlterField(
            model_name='practicums',
            name='id_model',
            field=models.TextField(blank=True, null=True, verbose_name='id для модального окна (без #)'),
        ),
        migrations.AlterField(
            model_name='practicums',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='id для модального окна (с #)'),
        ),
    ]
