# Generated by Django 5.0.6 on 2024-08-09 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practicums', '0012_practicums_link_web_alter_practicums_id_model_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='practicums',
            table='practi',
        ),
    ]
