# Generated by Django 5.0.6 on 2024-08-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efir',
            name='duration',
            field=models.TimeField(),
        ),
    ]
