# Generated by Django 5.0.6 on 2024-08-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efiry', '0002_alter_efir_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efir',
            name='duration',
            field=models.TextField(blank=True, null=True, verbose_name='Длительность'),
        ),
    ]
