# Generated by Django 5.0.6 on 2024-08-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_img_article_alter_post_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='body1',
        ),
        migrations.AddField(
            model_name='post',
            name='body2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
