# Generated by Django 5.0.6 on 2024-08-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews_images', verbose_name='Изображение'),
        ),
    ]
