# Generated by Django 5.0.6 on 2024-08-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.TimeField(verbose_name='Время проведения эфира'),
        ),
    ]
